name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Save node_modules
      run: tar -czf node_modules.tar.gz node_modules
      continue-on-error: true

    - name: Upload node_modules
      uses: actions/upload-artifact@v2
      with:
        name: node_modules
        path: node_modules.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Download node_modules
      uses: actions/download-artifact@v2
      with:
        name: node_modules
        path: .

    - name: Extract node_modules
      run: tar -xzf node_modules.tar.gz

    - name: Run tests and generate coverage
      run: npm run test:coverage

    - name: Install CodeClimate Test Reporter
      run: npm install -g codeclimate-test-reporter

    - name: Run CodeClimate Test Reporter
      env:
        CODECLIMATE_REPO_TOKEN: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        codeclimate-test-reporter < coverage/lcov.info