name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm login
        npm install
        make test-coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v2


    # - name: Run tests
    #   run: npm test
