name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate coverage
      run: npm run test:coverage

    - name: Install CodeClimate Test Reporter
      run: npm install -g codeclimate-test-reporter

    - name: Run CodeClimate Test Reporter
      env:
        CODECLIMATE_REPO_TOKEN: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        codeclimate-test-reporter < coverage/lcov.info
